export interface Episode {
  id: number;
  slug: string;
  date: string;
  readTime: number;
  tags: string[];
  published: boolean;
  title: {
    ko: string;
    en: string;
  };
  summary: {
    ko: string;
    en: string;
  };
}

export const episodes: Episode[] = [
  {
    id: 0,
    slug: '00',
    date: '2024-12-01',
    readTime: 4,
    tags: ['origin', 'family', 'motivation'],
    published: true,
    title: {
      ko: '페퍼 프로젝트의 시작',
      en: 'How the Pepper Project Started',
    },
    summary: {
      ko: '개발 지식이 거의 없는 테크 회사 임원이 가족을 위한 AI 어시스턴트를 만들기로 결심하기까지.',
      en: 'A tech executive with almost no development background decides to build an AI assistant for his family — and what made him actually start.',
    },
  },
  {
    id: 1,
    slug: '01',
    date: '2024-12-08',
    readTime: 6,
    tags: ['concept', 'architecture', 'state-machine'],
    published: true,
    title: {
      ko: '페퍼는 챗봇이 아니다',
      en: 'Pepper Is Not a Chatbot',
    },
    summary: {
      ko: 'Family Graph, Family Vault, 그리고 STATE A/B/C. 페퍼가 일반 챗봇과 근본적으로 다른 이유.',
      en: 'Family Graph, Family Vault, and STATE A/B/C. Why Pepper is fundamentally different from a regular chatbot.',
    },
  },
  {
    id: 2,
    slug: '02',
    date: '2024-12-15',
    readTime: 6,
    tags: ['architecture', 'design', 'documentation'],
    published: true,
    title: {
      ko: '코드보다 먼저 — 아키텍처 설계',
      en: 'Before the Code — Architecture Design',
    },
    summary: {
      ko: '코드 한 줄 치기 전에 반나절을 설계에 썼다. 비개발자가 AI와 함께 시스템 구조를 잡는 방법.',
      en: 'Half a day of design before a single line of code. How a non-developer builds system architecture with AI.',
    },
  },
  {
    id: 3,
    slug: '03',
    date: '2024-12-22',
    readTime: 7,
    tags: ['build-log', 'supabase', 'vercel'],
    published: true,
    title: {
      ko: 'Day 1 구현기 — "어, 이게 진짜 되네?"',
      en: 'Day 1 Build Log — "Wait, This Actually Works?"',
    },
    summary: {
      ko: '반나절 기획, 2시간 구현, 세션 51%. 모노레포 골격부터 Vercel 배포까지 — Day 1의 기록.',
      en: 'Half day planning, two hours building, 51% of session used. From monorepo skeleton to Vercel deploy — the Day 1 log.',
    },
  },
  {
    id: 4,
    slug: '04',
    date: '',
    readTime: 0,
    tags: [],
    published: false,
    title: { ko: 'Coming Soon', en: 'Coming Soon' },
    summary: { ko: '', en: '' },
  },
  {
    id: 5,
    slug: '05',
    date: '',
    readTime: 0,
    tags: [],
    published: false,
    title: { ko: 'Coming Soon', en: 'Coming Soon' },
    summary: { ko: '', en: '' },
  },
  {
    id: 6,
    slug: '06',
    date: '',
    readTime: 0,
    tags: [],
    published: false,
    title: { ko: 'Coming Soon', en: 'Coming Soon' },
    summary: { ko: '', en: '' },
  },
  {
    id: 7,
    slug: '07',
    date: '',
    readTime: 0,
    tags: [],
    published: false,
    title: { ko: 'Coming Soon', en: 'Coming Soon' },
    summary: { ko: '', en: '' },
  },
  {
    id: 8,
    slug: '08',
    date: '',
    readTime: 0,
    tags: [],
    published: false,
    title: { ko: 'Coming Soon', en: 'Coming Soon' },
    summary: { ko: '', en: '' },
  },
  {
    id: 9,
    slug: '09',
    date: '',
    readTime: 0,
    tags: [],
    published: false,
    title: { ko: 'Coming Soon', en: 'Coming Soon' },
    summary: { ko: '', en: '' },
  },
  {
    id: 10,
    slug: '10',
    date: '',
    readTime: 0,
    tags: [],
    published: false,
    title: { ko: 'Coming Soon', en: 'Coming Soon' },
    summary: { ko: '', en: '' },
  },
  {
    id: 11,
    slug: '11',
    date: '',
    readTime: 0,
    tags: [],
    published: false,
    title: { ko: 'Coming Soon', en: 'Coming Soon' },
    summary: { ko: '', en: '' },
  },
  {
    id: 12,
    slug: '12',
    date: '',
    readTime: 0,
    tags: [],
    published: false,
    title: { ko: 'Coming Soon', en: 'Coming Soon' },
    summary: { ko: '', en: '' },
  },
  {
    id: 13,
    slug: '13',
    date: '',
    readTime: 0,
    tags: [],
    published: false,
    title: { ko: 'Coming Soon', en: 'Coming Soon' },
    summary: { ko: '', en: '' },
  },
  {
    id: 14,
    slug: '14',
    date: '',
    readTime: 0,
    tags: [],
    published: false,
    title: { ko: 'Coming Soon', en: 'Coming Soon' },
    summary: { ko: '', en: '' },
  },
  {
    id: 15,
    slug: '15',
    date: '',
    readTime: 0,
    tags: [],
    published: false,
    title: { ko: 'Coming Soon', en: 'Coming Soon' },
    summary: { ko: '', en: '' },
  },
  {
    id: 16,
    slug: '16',
    date: '',
    readTime: 0,
    tags: [],
    published: false,
    title: { ko: 'Coming Soon', en: 'Coming Soon' },
    summary: { ko: '', en: '' },
  },
  {
    id: 17,
    slug: '17',
    date: '',
    readTime: 0,
    tags: [],
    published: false,
    title: { ko: 'Coming Soon', en: 'Coming Soon' },
    summary: { ko: '', en: '' },
  },
  {
    id: 18,
    slug: '18',
    date: '',
    readTime: 0,
    tags: [],
    published: false,
    title: { ko: 'Coming Soon', en: 'Coming Soon' },
    summary: { ko: '', en: '' },
  },
  {
    id: 19,
    slug: '19',
    date: '',
    readTime: 0,
    tags: [],
    published: false,
    title: { ko: 'Coming Soon', en: 'Coming Soon' },
    summary: { ko: '', en: '' },
  },
];
