export interface Episode {
  id: number;
  slug: string;
  date: string;
  readTime: number;
  tags: string[];
  published: boolean;
  title: {
    ko: string;
    en: string;
  };
  summary: {
    ko: string;
    en: string;
  };
}

export const episodes: Episode[] = [
  {
    id: 0,
    slug: '00',
    date: '2024-12-01',
    readTime: 4,
    tags: ['origin', 'naming'],
    published: true,
    title: {
      ko: '왜 페퍼라고 이름 붙였나',
      en: 'Why I Named It Pepper',
    },
    summary: {
      ko: '자비스라는 이름 대신 페퍼를 선택한 이유. 이 프로젝트가 무엇을 만들려고 하는지에 대한 첫 번째 기록.',
      en: 'Why I chose Pepper over Jarvis — and what that choice says about what I\'m actually trying to build.',
    },
  },
  {
    id: 1,
    slug: '01',
    date: '2024-12-08',
    readTime: 5,
    tags: ['concept', 'AI assistant'],
    published: true,
    title: {
      ko: '자비스의 문제',
      en: 'The Problem With Jarvis',
    },
    summary: {
      ko: '우리가 상상하는 AI 어시스턴트의 원형, 자비스. 그런데 자비스는 왜 실제로 쓸 수 없는 걸까.',
      en: 'Jarvis is the archetype we all imagine. But Jarvis is fictional for a reason — here\'s what\'s actually missing.',
    },
  },
  {
    id: 2,
    slug: '02',
    date: '',
    readTime: 0,
    tags: [],
    published: false,
    title: { ko: 'Coming Soon', en: 'Coming Soon' },
    summary: { ko: '', en: '' },
  },
  {
    id: 3,
    slug: '03',
    date: '',
    readTime: 0,
    tags: [],
    published: false,
    title: { ko: 'Coming Soon', en: 'Coming Soon' },
    summary: { ko: '', en: '' },
  },
  {
    id: 4,
    slug: '04',
    date: '',
    readTime: 0,
    tags: [],
    published: false,
    title: { ko: 'Coming Soon', en: 'Coming Soon' },
    summary: { ko: '', en: '' },
  },
  {
    id: 5,
    slug: '05',
    date: '',
    readTime: 0,
    tags: [],
    published: false,
    title: { ko: 'Coming Soon', en: 'Coming Soon' },
    summary: { ko: '', en: '' },
  },
  {
    id: 6,
    slug: '06',
    date: '',
    readTime: 0,
    tags: [],
    published: false,
    title: { ko: 'Coming Soon', en: 'Coming Soon' },
    summary: { ko: '', en: '' },
  },
  {
    id: 7,
    slug: '07',
    date: '',
    readTime: 0,
    tags: [],
    published: false,
    title: { ko: 'Coming Soon', en: 'Coming Soon' },
    summary: { ko: '', en: '' },
  },
  {
    id: 8,
    slug: '08',
    date: '',
    readTime: 0,
    tags: [],
    published: false,
    title: { ko: 'Coming Soon', en: 'Coming Soon' },
    summary: { ko: '', en: '' },
  },
  {
    id: 9,
    slug: '09',
    date: '',
    readTime: 0,
    tags: [],
    published: false,
    title: { ko: 'Coming Soon', en: 'Coming Soon' },
    summary: { ko: '', en: '' },
  },
  {
    id: 10,
    slug: '10',
    date: '',
    readTime: 0,
    tags: [],
    published: false,
    title: { ko: 'Coming Soon', en: 'Coming Soon' },
    summary: { ko: '', en: '' },
  },
  {
    id: 11,
    slug: '11',
    date: '',
    readTime: 0,
    tags: [],
    published: false,
    title: { ko: 'Coming Soon', en: 'Coming Soon' },
    summary: { ko: '', en: '' },
  },
  {
    id: 12,
    slug: '12',
    date: '',
    readTime: 0,
    tags: [],
    published: false,
    title: { ko: 'Coming Soon', en: 'Coming Soon' },
    summary: { ko: '', en: '' },
  },
  {
    id: 13,
    slug: '13',
    date: '',
    readTime: 0,
    tags: [],
    published: false,
    title: { ko: 'Coming Soon', en: 'Coming Soon' },
    summary: { ko: '', en: '' },
  },
  {
    id: 14,
    slug: '14',
    date: '',
    readTime: 0,
    tags: [],
    published: false,
    title: { ko: 'Coming Soon', en: 'Coming Soon' },
    summary: { ko: '', en: '' },
  },
  {
    id: 15,
    slug: '15',
    date: '',
    readTime: 0,
    tags: [],
    published: false,
    title: { ko: 'Coming Soon', en: 'Coming Soon' },
    summary: { ko: '', en: '' },
  },
  {
    id: 16,
    slug: '16',
    date: '',
    readTime: 0,
    tags: [],
    published: false,
    title: { ko: 'Coming Soon', en: 'Coming Soon' },
    summary: { ko: '', en: '' },
  },
  {
    id: 17,
    slug: '17',
    date: '',
    readTime: 0,
    tags: [],
    published: false,
    title: { ko: 'Coming Soon', en: 'Coming Soon' },
    summary: { ko: '', en: '' },
  },
  {
    id: 18,
    slug: '18',
    date: '',
    readTime: 0,
    tags: [],
    published: false,
    title: { ko: 'Coming Soon', en: 'Coming Soon' },
    summary: { ko: '', en: '' },
  },
  {
    id: 19,
    slug: '19',
    date: '',
    readTime: 0,
    tags: [],
    published: false,
    title: { ko: 'Coming Soon', en: 'Coming Soon' },
    summary: { ko: '', en: '' },
  },
];
